# Generated by Django 5.2.13 on 2026-05-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(db_index=True, help_text='IATA or ICAO airport code', max_length=10, unique=True)),
                ('icao_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('city_code', models.CharField(db_index=True, max_length=10)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(db_index=True, max_length=255)),
                ('country_code', models.CharField(db_index=True, max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('timezone', models.CharField(blank=True, help_text='Example: Asia/Tashkent', max_length=100, null=True)),
                ('airport_type', models.CharField(choices=[('international', 'International'), ('domestic', 'Domestic'), ('private', 'Private'), ('military', 'Military'), ('cargo', 'Cargo')], default='international', max_length=20)),
                ('terminals', models.PositiveIntegerField(default=1)),
                ('runways', models.PositiveIntegerField(default=1)),
                ('elevation_ft', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('supports_cargo', models.BooleanField(default=False)),
                ('supports_international_flights', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'airports',
                'ordering': ['country', 'city', 'name'],
                'indexes': [models.Index(fields=['airport_code'], name='airports_airport_de092f_idx'), models.Index(fields=['icao_code'], name='airports_icao_co_9980b3_idx'), models.Index(fields=['city'], name='airports_city_2f0293_idx'), models.Index(fields=['city_code'], name='airports_city_co_96eef1_idx'), models.Index(fields=['country'], name='airports_country_77d1cf_idx'), models.Index(fields=['country_code'], name='airports_country_e0419a_idx'), models.Index(fields=['name'], name='airports_name_2bfdb6_idx')],
            },
        ),
    ]
